export interface GameTemplate {
  id: string;
  title: string;
  description: string;
  icon: string;
  items: string[];
}

export const gameTemplates: GameTemplate[] = [
  {
    id: "holiday-dinner",
    title: "Holiday Dinner",
    description: "Classic family gathering moments",
    icon: "🦃",
    items: [
      "Someone arrives late",
      "Kid won't eat vegetables",
      "Political debate starts",
      "Someone falls asleep",
      "Wine spills",
      "Dad tells same joke",
      "Burnt food",
      "Missing ingredient",
      "Phone at dinner table",
      "Baby cries",
      "Dog begs for food",
      "Someone complains about weather",
      "Awkward silence",
      "Food gets cold",
      "Dessert forgotten",
      "Wrong dietary restriction",
      "TV too loud",
      "Kids table chaos",
      "Someone leaves early",
      "Group photo attempt",
      "Story from childhood",
      "Surprise guest",
      "Kitchen disaster",
      "Leftovers debate",
      "Thank you speech",
    ],
  },
  {
    id: "road-trip",
    title: "Road Trip",
    description: "Long drive entertainment",
    icon: "🚗",
    items: [
      "Are we there yet?",
      "Bathroom break needed",
      "Wrong turn taken",
      "Snacks dropped",
      "Music disagreement",
      "GPS recalculating",
      "Traffic jam",
      "Someone sleeping",
      "License plate game",
      "Fast food stop",
      "Gas station visit",
      "Argument about directions",
      "Phone battery dies",
      "Rest stop break",
      "Backseat complaint",
      "Radio static",
      "Roadside attraction",
      "Speed limit debate",
      "AC/Heat argument",
      "Forgot something",
      "Scenic photo stop",
      "Road construction",
      "Drive-thru order wrong",
      "Map reading confusion",
      "Sing-along moment",
    ],
  },
  {
    id: "family-reunion",
    title: "Family Reunion",
    description: "Extended family gathering",
    icon: "👨‍👩‍👧‍👦",
    items: [
      "Name forgotten",
      "Baby passed around",
      "Old photo shared",
      "Height comparison",
      "College questions",
      "Dating questions",
      "Job questions",
      "Health advice given",
      "Family tree confusion",
      "Childhood embarrassment",
      "Surprise announcement",
      "Group photo chaos",
      "Kids running wild",
      "Food preferences ignored",
      "Someone cries",
      "Generational gap moment",
      "Technology help needed",
      "Family gossip",
      "Who looks like who",
      "Memory lane story",
      "Future plans discussed",
      "Gift exchange",
      "Recipe requested",
      "Contact info exchanged",
      "Promise to visit more",
    ],
  },
  {
    id: "video-call",
    title: "Video Call",
    description: "Virtual meeting bingo",
    icon: "💻",
    items: [
      "Can you hear me?",
      "You're on mute",
      "Connection issues",
      "Pet appears",
      "Kid interrupts",
      "Background noise",
      "Camera off",
      "Screen share fail",
      "Echo feedback",
      "Frozen screen",
      "Awkward silence",
      "Talking over each other",
      "Virtual background",
      "Someone eating",
      "Phone notification",
      "Wrong window shared",
      "Someone drops off",
      "Can you see my screen?",
      "Recording question",
      "Doorbell rings",
      "Background activity",
      "Audio cuts out",
      "Chat message missed",
      "Meeting runs over",
      "Next meeting reminder",
    ],
  },
  {
    id: "birthday-party",
    title: "Birthday Party",
    description: "Birthday celebration moments",
    icon: "🎂",
    items: [
      "Candles won't light",
      "Singing off-key",
      "Wish takes forever",
      "Gift wrap struggle",
      "Cake mess",
      "Photo with cake",
      "Age joke",
      "Surprise element",
      "Party hat refused",
      "Balloon pops",
      "Gift card given",
      "Someone cries",
      "Sugar rush",
      "Game chaos",
      "Present envy",
      "Thank you reminded",
      "Leftover cake",
      "Clean up time",
      "Party favor forgotten",
      "Group singing",
      "Special tradition",
      "Memory shared",
      "Next year mentioned",
      "Social media post",
      "Best party ever said",
    ],
  },
];
